export const ADD_SONG = "ADD_SONG";
export const CREATE_PLAYLIST = "CREATE_PLAYLIST";
export const ADD_TO_PLAYLIST = "ADD_TO_PLAYLIST";
export const ADD_FEATURED_PLAYLIST = "ADD_FEATURED_PLAYLIST";
export const ADD_USER_PLAYLIST = "ADD_USER_PLAYLIST";
export const ADD_AUTOCOMPLETE_RESULTS = "ADD_AUTOCOMPLETE_RESULTS";
export const ADD_FAVOURITES = "ADD_FAVOURITES";